version: '3'
services:

  web:
    restart: "no"
    command: "${WEB_TEST_START_COMMAND}"

  api:
    restart: "no"
    command: /usr/bin/wait-for.sh prisma:${PRISMA_EXPOSE_PORT} -- ${API_TEST_START_COMMAND}
