version: '3'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    build:
      context: ./web
    command: "${WEB_START_COMMAND}"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${WEB_HOST}
      - VIRTUAL_PORT=80
    volumes:
      - ./web/:/opt/app
      - /opt/app/node_modules

  auth:
    build:
      context: ./auth
    command: ${AUTH_START_COMMAND}

    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${AUTH_HOST}
      - VIRTUAL_PORT=80
      - MONGO_HOST=mongodb://auth_db/auth
      - JWT_SECRET
    volumes:
      - ./auth/:/opt/app
      - /opt/app/node_modules

  auth_db:
    image: "mongo"
    ports:
      - "27017"

  api:
    build:
      context: ./api

    command: ${API_START_COMMAND}

    expose:
      - "80"

    environment:
      - VIRTUAL_HOST=${API_HOST}
      - VIRTUAL_PORT=80
      - PRISMA_HOST=http://prisma
      - JWT_SECRET

    volumes:
      - ./api/:/opt/app
      - /opt/app/node_modules

  prisma:
    image: prismagraphql/prisma:1.16
    restart: always
    ports:
    - "80"
    environment:
      PRISMA_CONFIG: |
        port: 80
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            migrations: true

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
